### ISSUE TITLE
Installation instructions doesn't work

### ISSUE THREAD

**Issue by mfocuz** [azlux/MumbleRadioPlayer#10]
# ./mumbleRadioPlayer.py
Traceback (most recent call last):
  File "./mumbleRadioPlayer.py", line 13, in <module>
    import pymumble.pymumble_py3 as pymumble
ImportError: No module named pymumble.pymumble_py3
mfocuz@host:~/bg_workers/MumbleRadioPlayer$ ls -l pymumble/
total 68
-rw-r--r-- 1 mfocuz mfocuz  8507 Sep  7 21:56 API.md
-rw-r--r-- 1 mfocuz mfocuz 35821 Sep  7 21:56 LICENSE
-rw-r--r-- 1 mfocuz mfocuz  3759 Sep  7 21:56 README.md
-rw-r--r-- 1 mfocuz mfocuz   217 Sep  7 21:56 TODO
drwxr-xr-x 2 mfocuz mfocuz  4096 Sep  7 21:56 pymumble_py3
-rw-r--r-- 1 mfocuz mfocuz    31 Sep  7 21:56 requirements.txt
-rw-r--r-- 1 mfocuz mfocuz   991 Sep  7 21:56 setup.py

**Comment by Lartza** [comment]
You need https://github.com/azlux/pymumble

```
git clone https://github.com/azlux/MumbleRadioPlayer.git
git submodule update --init
```

**Comment by azlux** [comment]
@Lartza it's do the same with `git clone --recurse-submodules https://github.com/azlux/MumbleRadioPlayer.git` it's strange the command hasn't worked !

**Comment by mfocuz** [comment]
Yeah, I run with --recurse-submodules. MAke it work with moving pymumble_py3 to current dir and rename to pymumble. Python 3.2.3, debian.

**Comment by azlux** [comment]
That is weird. 
look what I have : 
```
drwxr-xr-x  9 azlux azlux  280 Sep  8 11:39 .git
drwxr-xr-x  3 azlux azlux  220 Sep  8 11:39 pymumble
-rw-r--r--  1 azlux azlux 1.2K Sep  8 11:39 configuration.ini
-rw-r--r--  1 azlux azlux 1.1K Sep  8 11:39 .gitignore
-rw-r--r--  1 azlux azlux  108 Sep  8 11:39 .gitmodules
-rw-r--r--  1 azlux azlux  17K Sep  8 11:39 LICENCE.md
-rw-r--r--  1 azlux azlux  12K Sep  8 11:39 mumbleRadioPlayer.py
-rw-r--r--  1 azlux azlux 3.1K Sep  8 11:39 README.md
-rw-r--r--  1 azlux azlux   31 Sep  8 11:39 requirements.txt
```
What is you git version `git --version` ? I don't know why you have the folder named pymumble_py3 !

**Comment by mfocuz** [comment]
```
> mfocuz@orion:~/bg_workers/MumbleRadioPlayer$ ls
> LICENCE.md  README.md  configuration.ini  mumbleRadioPlayer.py	pymumble  requirements.txt
> mfocuz@orion:~/bg_workers/MumbleRadioPlayer$ ls pymumble/
> API.md	LICENSE  README.md  TODO  pymumble_py3	requirements.txt  setup.py
> mfocuz@orion:~/bg_workers/MumbleRadioPlayer$ git --version
> git version 1.7.10.4
> mfocuz@orion:~/bg_workers/MumbleRadioPlayer$ ./mumbleRadioPlayer.py
> Traceback (most recent call last):
>   File "./mumbleRadioPlayer.py", line 13, in <module>
>     import pymumble.pymumble_py3 as pymumble
> ImportError: No module named pymumble.pymumble_py3
```

**Comment by azlux** [comment]
I think it's more a python issue solved into pyhon3.4 with the PEP 451. I use python3.5 and python3.6 and the import module by subfolder (pymumble.pymumble_py3) is working well.
I'm not sure, but maybe with a empty file into pymumble folder named `__init__.py` will work !

**Comment by Lartza** [comment]
It's more likely https://docs.python.org/3/whatsnew/3.3.html#using-importlib-as-the-implementation-of-import
@azlux Maybe add an indication to pymumble and possibly MumbleRadioPlayer too that 3.3 or newer is required? I'd say it's fine to not support 3.2, only Debian oldoldstable has that and both oldstable and Ubuntu 14.04 have a newer version.
@mfocuz Upgrade to 3.3 or later :) pyenv or similar might be helpful in this. Might also consider upgrading Debian since wheezy EOL is 31st May 2018. Stretch has PHP7.0 among other great upgrades ;)

EDIT: And I did test 3.3.6 to not have the import error. Might have additional issues but hopefully not.

**Comment by mfocuz** [comment]
ok, thx
