### ISSUE TITLE
Logging - no timestamping and no filelogging

### ISSUE THREAD

**Issue by Glowsome** [azlux/MumbleRadioPlayer#14]
The current bot does not have timestamping in the logging which is outputted to console
In some cases this is preferred for backtracking issues.
Console-output is a means, but this gest lost after killing/relaunching the bot so not always enough to keep track

I have created a fork to work on this, but it may be a while before i can deliver, as i am at the point of switching jobs... 

First assignment in this (my) fork will be to add timestamping to the already available console-output
Then expanding it to file-logging (future path)

**Comment by azlux** [comment]
hi.
it's good to have datetime ito the output. I will look to it. Fell free to pull request.
For the logfile, it's not the goal to have it into the bot.
Use the `tee` function if you need it. Or use supervisor, it will take care of your service with logging into a file.
Az
