### ISSUE TITLE
Invalid data found when processing input

### ISSUE THREAD

**Issue by ayockel** [azlux/MumbleRadioPlayer#15]
I'm able to successfully connect to my server, but when I try to play any youtube video it shows 

https://www.youtube.com/watch?v=uc6f_2nPSX8: Invalid data found when processing input

I compiled ffmpeg with --enable-openssl, is there anything else that needs to be enabled?

**Comment by Lartza** [comment]
As the name implies the bot plays radio streams. For YouTube playback try https://github.com/matthieugrieger/mumbledj, https://bitbucket.org/Flandoo/mumblecop or https://github.com/TinyMan/node-jeanne

**Comment by azlux** [comment]
You can check this new projet https://github.com/azlux/botamusique
URL (youtube, soundcloud...), Radio and local files playing. It's almost ready.
