### ISSUE TITLE
NonType

### ISSUE THREAD

**Issue by ajmandourah** [azlux/MumbleRadioPlayer#7]
Hey,

I am getting these kind of error:

> Traceback (most recent call last):
  File "mumbleRadioPlayer.py", line 287, in <module>
    playbot = MumbleRadioPlayer()
  File "mumbleRadioPlayer.py", line 50, in __init__
    self.set_comment()
  File "mumbleRadioPlayer.py", line 207, in set_comment
    self.mumble.users.myself.comment(txt + "<p /> " + self.config.get('bot', 'comment'))
AttributeError: 'NoneType' object has no attribute 'comment'

**Comment by azlux** [comment]
I think you have removed the "comment" parameter from the configuration file.

**Comment by ajmandourah** [comment]
Nope. its there. I haven't change anything from the original files as I cloned them.

**Comment by azlux** [comment]
Look like the bot wasn't connected. So the bot cannot set his comment when he is supposed to be ready. Can you check you mumble log ? Maybe you reject the connection. Do you see the bot connected into you server ?

**Comment by azlux** [comment]
Found it ! Happening to me today.
It's when you fail the connection because it's a bad address for example.
check the `./mumbleRadioPlayer.py -s <address>`
